package com.pro100kryto.server.services.auth.connection;

public class AuthorizationInternalErrorException extends AuthorizationException {
    public AuthorizationInternalErrorException(Throwable cause) {
        super(cause);
    }
}
